version: '3.8'
services:
  db:
    image: postgres:15
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  web:
    build: .
    command: gunicorn skillswap.wsgi:application -b 0.0.0.0:8000
    env_file: .env
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
